import httpx
import os
import re
from datetime import datetime, timezone

GITLAB_TOKEN = os.getenv("GITLAB_TOKEN")
BASE_URL = "https://gitlab.com/api/v4"
HEADERS = {"PRIVATE-TOKEN": GITLAB_TOKEN}

AUTO_FIX_ENABLED = os.getenv("PIPELINEIQ_AUTO_FIX_MR", "false").lower() == "true"

async def create_auto_fix_mr(
    project_id: int,
    source_branch: str,
    commit_sha: str,
    pipeline_id: int,
    diagnosis_text: str,
    failed_job_names: list[str],
) -> str | None:
    """
    Creates a draft MR on GitLab that:
    1. Branches off the failing commit
    2. Adds a PIPELINEIQ_FIX.md file with the full diagnosis and fix plan
    3. Opens as a draft MR targeting the source branch

    Returns the MR URL on success, None on failure.
    The PIPELINEIQ_FIX.md approach means no risky auto-edits to production code —
    the developer reviews the diagnosis and applies the fix themselves.
    """
    if not AUTO_FIX_ENABLED:
        return None

    timestamp = datetime.now(timezone.utc).strftime("%Y%m%d%H%M%S")
    fix_branch = f"pipelineiq/auto-fix-pipeline-{pipeline_id}-{timestamp}"
    jobs_label = ", ".join(failed_job_names[:3])  # cap branch name length

    fix_file_content = _build_fix_file(
        diagnosis_text, failed_job_names, pipeline_id, commit_sha
    )

    async with httpx.AsyncClient(timeout=30) as client:
        branch_resp = await client.post(
            f"{BASE_URL}/projects/{project_id}/repository/branches",
            headers=HEADERS,
            json={"branch": fix_branch, "ref": commit_sha},
        )
        if branch_resp.status_code not in (200, 201):
            print(f"[auto_fix_mr] Branch creation failed: {branch_resp.text}")
            return None

        import base64
        encoded_content = base64.b64encode(fix_file_content.encode()).decode()

        commit_resp = await client.post(
            f"{BASE_URL}/projects/{project_id}/repository/files/PIPELINEIQ_FIX.md",
            headers=HEADERS,
            json={
                "branch": fix_branch,
                "content": fix_file_content,
                "encoding": "text",
                "commit_message": (
                    f"fix: PipelineIQ diagnosis for pipeline #{pipeline_id} "
                    f"[{jobs_label}]"
                ),
            },
        )
        if commit_resp.status_code not in (200, 201):
            print(f"[auto_fix_mr] File commit failed: {commit_resp.text}")
            return None

        mr_resp = await client.post(
            f"{BASE_URL}/projects/{project_id}/merge_requests",
            headers=HEADERS,
            json={
                "source_branch": fix_branch,
                "target_branch": source_branch,
                "title": f"Draft: PipelineIQ Fix — Pipeline #{pipeline_id} [{jobs_label}]",
                "description": _build_mr_description(
                    diagnosis_text, pipeline_id, commit_sha, failed_job_names
                ),
                "draft": True,
                "labels": "pipelineiq,auto-fix",
                "remove_source_branch": True,
            },
        )
        if mr_resp.status_code not in (200, 201):
            print(f"[auto_fix_mr] MR creation failed: {mr_resp.text}")
            return None

        mr_url = mr_resp.json().get("web_url", "")
        print(f"[auto_fix_mr] Draft MR created: {mr_url}")
        return mr_url


def _build_fix_file(
    diagnosis: str,
    job_names: list[str],
    pipeline_id: int,
    commit_sha: str,
) -> str:
    return f"""# PipelineIQ Auto-Fix Report

> **Auto-generated by PipelineIQ** — review and apply the fix plan below, then remove this file.

| Field | Value |
|-------|-------|
| Pipeline | #{pipeline_id} |
| Commit | `{commit_sha[:10]}` |
| Failed Jobs | {", ".join(job_names)} |

---

## Diagnosis & Fix Plan

{diagnosis}

---

*This file was created automatically. Once you've applied the fix, delete it and mark the MR as ready.*
"""


def _build_mr_description(
    diagnosis: str,
    pipeline_id: int,
    commit_sha: str,
    job_names: list[str],
) -> str:
    jobs_str = ", ".join(f"`{j}`" for j in job_names)
    short_sha = commit_sha[:10]
    return f"""## 🤖 PipelineIQ Auto-Fix Draft

This MR was automatically created by **PipelineIQ** after pipeline **#{pipeline_id}** failed
on commit `{short_sha}`.

**Failed jobs:** {jobs_str}

---

### What's in this MR

A `PIPELINEIQ_FIX.md` file has been added with the full Claude diagnosis and step-by-step
fix plan. **No production code has been modified** — this is intentional. Review the diagnosis,
apply the fixes manually, then delete `PIPELINEIQ_FIX.md` and mark this MR as Ready.

---

### Diagnosis Summary

{diagnosis[:2000]}{"..." if len(diagnosis) > 2000 else ""}

---

/assign me
/label ~pipelineiq ~needs-review
"""